-- Plus Shipping 配送元データ登録SQL（consignorsテーブル）
-- 生成日時: 2025/11/10 16:49:07
-- Shopify Shop ID: 81-test-store-plan-silver.myshopify.com
-- Store ID: 404
-- 用途: テストデータ
-- 注意: 既存のdetail_idを使い回しています

-- 1. 北海道 - 北海道配送センター（北海道庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '北海道配送センター（北海道庁）',
  '060-8588',
  '北海道',
  '札幌市中央区',
  '北3条西6丁目',
  '',
  '011-231-4111',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 2. 青森県 - 北東北配送センター（青森県庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '北東北配送センター（青森県庁）',
  '030-8570',
  '青森県',
  '青森市',
  '長島1-1-1',
  '',
  '017-722-1111',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 3. 宮城県 - 南東北配送センター（宮城県庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '南東北配送センター（宮城県庁）',
  '980-8570',
  '宮城県',
  '仙台市青葉区',
  '本町3-8-1',
  '',
  '022-211-2111',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 4. 東京都 - 関東配送センター（東京都庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '関東配送センター（東京都庁）',
  '163-8001',
  '東京都',
  '新宿区',
  '西新宿2-8-1',
  '',
  '03-5321-1111',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 5. 新潟県 - 信越配送センター（新潟県庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '信越配送センター（新潟県庁）',
  '950-8570',
  '新潟県',
  '新潟市中央区',
  '新光町4-1',
  '',
  '025-285-5511',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 6. 石川県 - 北陸配送センター（石川県庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '北陸配送センター（石川県庁）',
  '920-8580',
  '石川県',
  '金沢市',
  '鞍月1-1',
  '',
  '076-225-1111',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 7. 愛知県 - 中部配送センター（愛知県庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '中部配送センター（愛知県庁）',
  '460-8501',
  '愛知県',
  '名古屋市中区',
  '三の丸3-1-2',
  '',
  '052-961-2111',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 8. 大阪府 - 関西配送センター（大阪府庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '関西配送センター（大阪府庁）',
  '540-8570',
  '大阪府',
  '大阪市中央区',
  '大手前2',
  '',
  '06-6941-0351',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 9. 広島県 - 中国配送センター（広島県庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '中国配送センター（広島県庁）',
  '730-8511',
  '広島県',
  '広島市中区',
  '基町10-52',
  '',
  '082-228-2111',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 10. 香川県 - 四国配送センター（香川県庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '四国配送センター（香川県庁）',
  '760-8570',
  '香川県',
  '高松市',
  '番町4-1-10',
  '',
  '087-831-1111',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 11. 福岡県 - 北九州配送センター（福岡県庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '北九州配送センター（福岡県庁）',
  '812-8577',
  '福岡県',
  '福岡市博多区',
  '東公園7-7',
  '',
  '092-651-1111',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 12. 鹿児島県 - 南九州配送センター（鹿児島県庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '南九州配送センター（鹿児島県庁）',
  '890-8577',
  '鹿児島県',
  '鹿児島市',
  '鴨池新町10-1',
  '',
  '099-286-2111',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

-- 13. 沖縄県 - 沖縄配送センター（沖縄県庁）
INSERT INTO consignors (
  shopify_shop_id,
  store_id,
  japan_post_consignor_detail_id,
  sagawa_consignor_detail_id,
  yamato_consignor_detail_id,
  print_name,
  location_name,
  postal_code,
  prefecture,
  city,
  address,
  building,
  tel,
  delivery_usage,
  application_status,
  application_status_sagawa,
  application_status_yamato,
  deletion_requested
) VALUES (
  '81-test-store-plan-silver.myshopify.com',
  404,
  0,
  556,
  528,
  '',
  '沖縄配送センター（沖縄県庁）',
  '900-8570',
  '沖縄県',
  '那覇市',
  '泉崎1-2-2',
  '',
  '098-866-2333',
  1,
  'accepted',
  'accepted',
  'accepted',
  0
);

